---

- hosts: nginx
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Add Nginx Repo
      yum_repository:
        name: nginx
        description: Nginx Yum Repo
        baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
        gpgcheck: no
        enabled: yes
          
    - name: Install nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes

    - name: Enable service nginx
      systemd:
        name: nginx
        enabled: yes
        
    - name: ensure nginx is started
      systemd:
        state: started
        name: nginx
